---
# tasks file for mariadb

- name: Install MariaDB
  apt:
    name: mariadb-server
    state: present

- name: Import seed data (if provided)
  community.mysql.mysql_db:
    name: "app_db"
    state: "import"
    target: "/path/to/seed.sql"


...
